use ecommerce;
INSERT INTO Electronics VALUES(1,'Apple Iphone 12','Apple Iphone 12 is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(2,'Xiaomi Redmi 8','Xiaomi Redmi 8 is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(3,'Xiaomi Redmi 9','Xiaomi Redmi 9 is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(4,'Xiaomi Redmi Note 10 Pro','Xiaomi Redmi Note 10 Pro is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(5,'Vivo V28','Vivo V28 is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(6,'Oppo F64','Oppo F64 is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(7,'Lenovo Zenphone','Lenovo Zenphone is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(8,'HTC Desire','HTC Desire is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(9,'Huawei Air','Huawei Air is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(10,'Samsung Galaxy Note 5','Samsung Galaxy Note 5 is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(11,'Apple Iphone SE','Apple Iphone SE is a must to improve the productivity','Mobile Phone');
INSERT INTO Electronics VALUES(12,'Apple Macbook Air','Apple Macbook Air is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(13,'Lenovo Thinkpad HV324','Lenovo Thinkpad HV324 is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(14,'Dell Vostro H3424','Dell Vostro H3424 is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(15,'HP Pavillion','HP Pavillion is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(16,'Acer Aspire','Acer Aspire is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(17,'Apple Macbook Pro','Apple Macbook Pro is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(18,'HP Omen V2341','HP Omen V2341 is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(19,'Lenovo Ideapad S1234','Lenovo Ideapad S1234 is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(20,'Mi Notebook Horizon','Mi Notebook Horizon is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(21,'Dell Inspiron 3452','Dell Inspiron 3452 is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(22,'Asus Vivobook Ultra K14','Asus Vivobook Ultra K14 is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(23,'Acer One 14 Z2-485','Acer One 14 Z2-485 is a must to improve the productivity','Laptop');
INSERT INTO Electronics VALUES(24,'boat bassheads','boat bassheads is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(25,'boat rockerz 450 Bluetooth','boat rockerz 450 Bluetooth is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(26,'JBL T460BT','JBL T460BT is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(27,'Zebronics Zeb Thunder','Zebronics Zeb Thunder is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(28,'JBL C100SI','JBL C100SI is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(29,'Ptron Boom','Ptron Boom is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(30,'Sony MDR-Zx','Sony MDR-Zx is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(31,'JBL C115TWS','JBL C115TWS is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(32,'Boult Audio Bass heads','Boult Audio Bass heads is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(33,'Cosmic Byte Star Dust','Cosmic Byte Star Dust is a must to improve the productivity','Ear Phones');
INSERT INTO Electronics VALUES(34,'pTron Tangent Beat','pTron Tangent Beat is a must to improve the productivity','Ear Phones');
