use ecommerce;

INSERT INTO Retailer VALUES(1,'Nicolle','Nicolle@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(2,'Nigel','Nigel@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(3,'Nikhil','Nikhil@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(4,'Niki','Niki@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(5,'Nikia','Nikia@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(6,'Nikita','Nikita@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(7,'Nikki','Nikki@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(8,'Nikko','Nikko@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(9,'Niko','Niko@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(10,'Nikolai','Nikolai@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(11,'Nikolas','Nikolas@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(12,'Nikole','Nikole@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(13,'Nila','Nila@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(14,'Nilda','Nilda@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(15,'Nile','Nile@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(16,'Niles','Niles@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(17,'Nils','Nils@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(18,'Nim','Nim@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(19,'Nina','Nina@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(20,'Ninnie','Ninnie@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(21,'Nira','Nira@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(22,'Nita','Nita@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(23,'Noah','Noah@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(24,'Nobie','Nobie@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(25,'Noble','Noble@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(26,'Noe','Noe@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(27,'Noel','Noel@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(28,'Noelia','Noelia@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(29,'Noelle','Noelle@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(30,'Noemi','Noemi@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(31,'Noemie','Noemie@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(32,'Nohely','Nohely@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(33,'Nola','Nola@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(34,'Nolan','Nolan@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(35,'Nolen','Nolen@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(36,'Nolia','Nolia@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(37,'Nolie','Nolie@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(38,'Noma','Noma@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(39,'Nona','Nona@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(40,'Nonie','Nonie@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(41,'Nora','Nora@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(42,'Norah','Norah@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(43,'Norbert','Norbert@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(44,'Norberto','Norberto@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(45,'Noreen','Noreen@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(46,'Norene','Norene@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(47,'Noreta','Noreta@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(48,'Noretta','Noretta@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(49,'Norine','Norine@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(50,'Norita','Norita@gmail.com','Ahmedabad','Gujarat','India');
INSERT INTO Retailer VALUES(51,'Norma','Norma@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(52,'Norman','Norman@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(53,'Normand','Normand@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(54,'Norris','Norris@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(55,'North','North@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(56,'Norton','Norton@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(57,'Norval','Norval@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(58,'Norwood','Norwood@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(59,'Nova','Nova@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(60,'Novella','Novella@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(61,'Nunzio','Nunzio@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(62,'Nya','Nya@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(63,'Nyah','Nyah@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(64,'Nyasia','Nyasia@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(65,'Nyla','Nyla@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(66,'Nylah','Nylah@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(67,'Nyree','Nyree@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(68,'Oakley','Oakley@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(69,'Obe','Obe@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(70,'Obed','Obed@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(71,'Obie','Obie@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(72,'Ocie','Ocie@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(73,'Octa','Octa@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(74,'Octave','Octave@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(75,'Octavia','Octavia@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(76,'Octavie','Octavie@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(77,'Octavio','Octavio@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(78,'Octavius','Octavius@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(79,'Oda','Oda@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(80,'Odalis','Odalis@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(81,'Odalys','Odalys@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(82,'Oddie','Oddie@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(83,'Odelia','Odelia@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(84,'Odell','Odell@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(85,'Odessa','Odessa@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(86,'Odette','Odette@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(87,'Odie','Odie@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(88,'Odile','Odile@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(89,'Odin','Odin@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(90,'Odis','Odis@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(91,'Odus','Odus@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(92,'Ofelia','Ofelia@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(93,'Offie','Offie@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(94,'Ogden','Ogden@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(95,'Okey','Okey@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(96,'Ola','Ola@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(97,'Olaf','Olaf@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(98,'Olan','Olan@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(99,'Oland','Oland@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(100,'Olar','Olar@gmail.com','Gandhinagar','Gujarat','India');
INSERT INTO Retailer VALUES(101,'Ole','Ole@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(102,'Olen','Olen@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(103,'Olena','Olena@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(104,'Olene','Olene@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(105,'Oleta','Oleta@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(106,'Olevia','Olevia@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(107,'Oley','Oley@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(108,'Olga','Olga@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(109,'Olie','Olie@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(110,'Olin','Olin@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(111,'Olinda','Olinda@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(112,'Oline','Oline@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(113,'Oliva','Oliva@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(114,'Olive','Olive@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(115,'Oliver','Oliver@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(116,'Olivia','Olivia@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(117,'Olivine','Olivine@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(118,'Ollie','Ollie@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(119,'Olof','Olof@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(120,'Olympia','Olympia@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(121,'Oma','Oma@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(122,'Omar','Omar@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(123,'Omari','Omari@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(124,'Omarion','Omarion@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(125,'Omer','Omer@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(126,'Omie','Omie@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(127,'Ona','Ona@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(128,'Oneal','Oneal@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(129,'Oneida','Oneida@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(130,'Oneta','Oneta@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(131,'Oney','Oney@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(132,'Onie','Onie@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(133,'Onnie','Onnie@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(134,'Opal','Opal@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(135,'Opha','Opha@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(136,'Ophelia','Ophelia@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(137,'Ora','Ora@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(138,'Orah','Orah@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(139,'Oral','Oral@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(140,'Oralia','Oralia@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(141,'Oran','Oran@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(142,'Orange','Orange@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(143,'Orelia','Orelia@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(144,'Oren','Oren@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(145,'Orene','Orene@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(146,'Orie','Orie@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(147,'Orilla','Orilla@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(148,'Orin','Orin@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(149,'Orion','Orion@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(150,'Oris','Oris@gmail.com','Mumbai','Maharashtra','India');
INSERT INTO Retailer VALUES(151,'Orla','Orla@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(152,'Orland','Orland@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(153,'Orlando','Orlando@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(154,'Orlena','Orlena@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(155,'Orley','Orley@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(156,'Orlin','Orlin@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(157,'Orlo','Orlo@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(158,'Orma','Orma@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(159,'Orpha','Orpha@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(160,'Orra','Orra@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(161,'Orren','Orren@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(162,'Orrie','Orrie@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(163,'Orrin','Orrin@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(164,'Orris','Orris@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(165,'Orson','Orson@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(166,'Orval','Orval@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(167,'Orvel','Orvel@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(168,'Orvil','Orvil@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(169,'Orville','Orville@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(170,'Orvin','Orvin@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(171,'Orvis','Orvis@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(172,'Osa','Osa@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(173,'Osbaldo','Osbaldo@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(174,'Osborn','Osborn@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(175,'Osborne','Osborne@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(176,'Oscar','Oscar@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(177,'Osie','Osie@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(178,'Ossie','Ossie@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(179,'Osvaldo','Osvaldo@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(180,'Oswald','Oswald@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(181,'Oswaldo','Oswaldo@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(182,'Ota','Ota@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(183,'Otelia','Otelia@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(184,'Otha','Otha@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(185,'Othel','Othel@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(186,'Otho','Otho@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(187,'Otis','Otis@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(188,'Ott','Ott@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(189,'Ottie','Ottie@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(190,'Ottilia','Ottilia@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(191,'Ottilie','Ottilie@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(192,'Ottis','Ottis@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(193,'Otto','Otto@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(194,'Ouida','Ouida@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(195,'Ova','Ova@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(196,'Ovid','Ovid@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(197,'Ovila','Ovila@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(198,'Owen','Owen@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(199,'Owens','Owens@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(200,'Ozell','Ozell@gmail.com','Chennai','Tamil Nadu','India');
INSERT INTO Retailer VALUES(201,'Ozella','Ozella@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(202,'Ozie','Ozie@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(203,'Ozzie','Ozzie@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(204,'Pablo','Pablo@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(205,'Page','Page@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(206,'Paige','Paige@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(207,'Pairlee','Pairlee@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(208,'Paisley','Paisley@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(209,'Paityn','Paityn@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(210,'Pallie','Pallie@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(211,'Palma','Palma@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(212,'Palmer','Palmer@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(213,'Paloma','Paloma@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(214,'Pam','Pam@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(215,'Pamala','Pamala@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(216,'Pamela','Pamela@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(217,'Pamelia','Pamelia@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(218,'Pamella','Pamella@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(219,'Pandora','Pandora@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(220,'Pansy','Pansy@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(221,'Paola','Paola@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(222,'Paralee','Paralee@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(223,'Paris','Paris@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(224,'Park','Park@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(225,'Parker','Parker@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(226,'Parlee','Parlee@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(227,'Parley','Parley@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(228,'Parrish','Parrish@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(229,'Parthenia','Parthenia@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(230,'Pascal','Pascal@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(231,'Pasquale','Pasquale@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(232,'Pat','Pat@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(233,'Pate','Pate@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(234,'Patience','Patience@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(235,'Patric','Patric@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(236,'Patrica','Patrica@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(237,'Patrice','Patrice@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(238,'Patricia','Patricia@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(239,'Patrick','Patrick@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(240,'Patsy','Patsy@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(241,'Patti','Patti@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(242,'Pattie','Pattie@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(243,'Patty','Patty@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(244,'Paul','Paul@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(245,'Paula','Paula@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(246,'Pauletta','Pauletta@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(247,'Paulette','Paulette@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(248,'Paulina','Paulina@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(249,'Pauline','Pauline@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(250,'Paulo','Paulo@gmail.com','Kochi','Kerala','India');
INSERT INTO Retailer VALUES(251,'Paxton','Paxton@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(252,'Payten','Payten@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(253,'Payton','Payton@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(254,'Pearl','Pearl@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(255,'Pearla','Pearla@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(256,'Pearle','Pearle@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(257,'Pearlene','Pearlene@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(258,'Pearley','Pearley@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(259,'Pearlie','Pearlie@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(260,'Pearline','Pearline@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(261,'Pearly','Pearly@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(262,'Pedro','Pedro@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(263,'Peggie','Peggie@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(264,'Peggy','Peggy@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(265,'Penelope','Penelope@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(266,'Penni','Penni@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(267,'Pennie','Pennie@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(268,'Penny','Penny@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(269,'Pepper','Pepper@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(270,'Percival','Percival@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(271,'Percy','Percy@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(272,'Perla','Perla@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(273,'Perley','Perley@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(274,'Permelia','Permelia@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(275,'Pernell','Pernell@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(276,'Perri','Perri@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(277,'Perry','Perry@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(278,'Pershing','Pershing@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(279,'Pete','Pete@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(280,'Peter','Peter@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(281,'Petra','Petra@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(282,'Peyton','Peyton@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(283,'Phebe','Phebe@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(284,'Pheobe','Pheobe@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(285,'Phil','Phil@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(286,'Philip','Philip@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(287,'Phillip','Phillip@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(288,'Phillis','Phillis@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(289,'Philo','Philo@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(290,'Philomena','Philomena@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(291,'Philomene','Philomene@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(292,'Phoebe','Phoebe@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(293,'Phoenix','Phoenix@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(294,'Phylicia','Phylicia@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(295,'Phylis','Phylis@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(296,'Phyliss','Phyliss@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(297,'Phyllis','Phyllis@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(298,'Pierce','Pierce@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(299,'Pierre','Pierre@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(300,'Pink','Pink@gmail.com','Hyderabad','Telangana','India');
INSERT INTO Retailer VALUES(301,'Pinkey','Pinkey@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(302,'Pinkie','Pinkie@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(303,'Pinkney','Pinkney@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(304,'Piper','Piper@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(305,'Pleas','Pleas@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(306,'Pleasant','Pleasant@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(307,'Ples','Ples@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(308,'Pluma','Pluma@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(309,'Plummer','Plummer@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(310,'Polk','Polk@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(311,'Pollie','Pollie@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(312,'Polly','Polly@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(313,'Porfirio','Porfirio@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(314,'Porsche','Porsche@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(315,'Porsha','Porsha@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(316,'Porter','Porter@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(317,'Portia','Portia@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(318,'Posey','Posey@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(319,'Powell','Powell@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(320,'Pranav','Pranav@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(321,'Pratt','Pratt@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(322,'Precious','Precious@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(323,'Prentice','Prentice@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(324,'Prentiss','Prentiss@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(325,'Presley','Presley@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(326,'Press','Press@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(327,'Preston','Preston@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(328,'Price','Price@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(329,'Pricilla','Pricilla@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(330,'Primus','Primus@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(331,'Prince','Prince@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(332,'Princess','Princess@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(333,'Priscila','Priscila@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(334,'Priscilla','Priscilla@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(335,'Prosper','Prosper@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(336,'Prudence','Prudence@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(337,'Prudie','Prudie@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(338,'Pryor','Pryor@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(339,'Purl','Purl@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(340,'Qiana','Qiana@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(341,'Queen','Queen@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(342,'Queenie','Queenie@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(343,'Quentin','Quentin@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(344,'Quiana','Quiana@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(345,'Quincy','Quincy@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(346,'Quinn','Quinn@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(347,'Quint','Quint@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(348,'Quinten','Quinten@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(349,'Quintin','Quintin@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(350,'Quinton','Quinton@gmail.com','Delhi','Delhi','India');
INSERT INTO Retailer VALUES(351,'Rachael','Rachael@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(352,'Racheal','Racheal@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(353,'Rachel','Rachel@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(354,'Rachelle','Rachelle@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(355,'Racquel','Racquel@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(356,'Rae','Rae@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(357,'Raegan','Raegan@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(358,'Raekwon','Raekwon@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(359,'Raelynn','Raelynn@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(360,'Rafael','Rafael@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(361,'Rafaela','Rafaela@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(362,'Rafe','Rafe@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(363,'Ragna','Ragna@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(364,'Raheem','Raheem@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(365,'Rahn','Rahn@gmail.com','Kolkata','West Bengal','India');
INSERT INTO Retailer VALUES(366,'Rahsaan','Rahsaan@gmail.com','Kolkata','West Bengal','India');
