use ecommerce;
INSERT INTO Clothes VALUES(45,'Arrow: Mens Regular fit solid shirt',STR_TO_DATE('01-10-2020', '%d-%m-%Y'),'Arrow: Mens Regular fit solid shirt is very cool to wear.','Arrow');
INSERT INTO Clothes VALUES(46,'Louis Philippe: Mens Regular fit formal shirt',STR_TO_DATE('04-11-2020', '%d-%m-%Y'),'Louis Philippe: Mens Regular fit formal shirt is very cool to wear.','Louis Philippe');
INSERT INTO Clothes VALUES(47,'Tommy Hilfiger: Mens Regular fit formal shirt',STR_TO_DATE('10-11-2020', '%d-%m-%Y'),'Tommy Hilfiger: Mens Regular fit formal shirt is very cool to wear.','Tommy Hilfiger');
INSERT INTO Clothes VALUES(48,'Mens Bomber Jacket',STR_TO_DATE('10-12-2020', '%d-%m-%Y'),'Mens Bomber Jacket is very cool to wear.','Fort Collins');
INSERT INTO Clothes VALUES(49,'Mens Cotton Turtle Neck Sweater',STR_TO_DATE('11-09-2018', '%d-%m-%Y'),'Mens Cotton Turtle Neck Sweater is very cool to wear.','Denimholic');
INSERT INTO Clothes VALUES(50,'Round Neck Sweater',STR_TO_DATE('12-07-2018', '%d-%m-%Y'),'Round Neck Sweater is very cool to wear.','Alan Jones');
INSERT INTO Clothes VALUES(51,'Blended Sweater',STR_TO_DATE('13-05-2017', '%d-%m-%Y'),'Blended Sweater is very cool to wear.','Aarbee');
INSERT INTO Clothes VALUES(52,'Relaxed Jeans',STR_TO_DATE('20-07-2019', '%d-%m-%Y'),'Relaxed Jeans is very cool to wear.','Ben Martin');
INSERT INTO Clothes VALUES(53,'Slim Fit Denim Jeans',STR_TO_DATE('12-12-2020', '%d-%m-%Y'),'Slim Fit Denim Jeans is very cool to wear.','Urbano Fashion');
INSERT INTO Clothes VALUES(54,'Cut and Sew Denim Jeans',STR_TO_DATE('13-12-2020', '%d-%m-%Y'),'Cut and Sew Denim Jeans is very cool to wear.','Campus Sutra');
